language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bearshadow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -t bearshadow/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t bearshadow/multi-client ./client
  - docker build -t bearshadow/multi-nginx ./nginx
  - docker build -t bearshadow/multi-server ./server
  - docker build -t bearshadow/multi-worker ./worker
  # Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push Docker hub
  - docker push bearshadow/multi-client
  - docker push bearshadow/multi-nginx
  - docker push bearshadow/multi-server
  - docker push bearshadow/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-211563887540"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY